Init

diff --git a/templates/relay.init.erb b/templates/relay.init.erb
--- a/templates/relay.init.erb
+++ b/templates/relay.init.erb
@@ -1,97 +1,132 @@
-#!/bin/bash
+#!/bin/sh
+# Init script for Carbon-C-Relay
+# Maintained by Yelp
+# Implemented based on LSB Core 3.1:
+#   * Sections: 20.2, 20.3
 #
-#	/etc/rc.d/init.d/relay
-#
-#	relay    Startup script for the carbon-c-relay metrics aggregation daemon
-#	Packaged for the BBC by Matthew Hollick <matthew@mayan-it.co.uk>
-#
-# description: Carbon-like graphite line mode relay.\n
-#\n
-#This project aims to be a replacement of the original Carbon relay\n
-#\n
-#The main reason to build a replacement is performance and configurability.\n
-#Carbon is single threaded, and sending metrics to multiple consistent-hash\n
-#clusters requires chaining of relays. This project provides a multithreaded\n
-#relay which can address multiple targets and clusters for each and every\n
-#metric based on pattern matches.\n
-#
-# chkconfig: 2345 80 80
-#
-# config: /etc/relay.conf
-# pidfile: /var/run/carbon/relay.pid
+### BEGIN INIT INFO
+# Provides:          carbon-c-relay
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Carbon-c-relay
+# Description:       Carbon-c-relay
+### END INIT INFO
 
-# Source function library.
-RETVAL=0
-PROG="relay"
-DAEMON_CONFIG=/etc/${PROG}.conf
-DAEMON=/usr/bin/${PROG}
-ARGS="-r <%= @config_file %> -i <%= @interface %> \
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+export PATH
+
+name=relay
+program=/usr/bin/relay
+args="-f <%= @config_file %> \
       -p <%= @port %> -w <%= @workers %> \
       -b <%= @batch_size %> -q <%= @queue_size %> \
       -S <%= @statistics %>"
-PID_FILE=/var/run/carbon/${PROG}.pid
-LOCK_FILE=/var/lock/subsys/${PROG}
-LOG_FILE=<%= @log_file %>
-DAEMON_USER="www-data"
-FQDN=$(hostname --long)
+pidfile="/var/run/$name.pid"
+
+[ -r /etc/default/$name ] && . /etc/default/$name
+[ -r /etc/sysconfig/$name ] && . /etc/sysconfig/$name
 
 start() {
-  if check_status > /dev/null; then
-    echo "Carbon C Relay is already running"
-    exit 0
-  fi
 
-  echo -n $"Starting Carbon C Relay: "
-  daemonize -u ${DAEMON_USER} -p ${PID_FILE} -l ${LOCK_FILE} -a -e <%= @log_file %> -o <%= @log_file %> ${DAEMON} ${ARGS} -H ${FQDN} -f ${DAEMON_CONFIG}
-  RETVAL=$?
-  echo ""
-  return ${RETVAL}
+  # Run the program!
+  exec ""\"$program\" $args" >> /var/log/$name.log 2> /var/log/$name.err &
+
+  # Generate the pidfile from here. If we instead made the forked process
+  # generate it there will be a race condition between the pidfile writing
+  # and a process possibly asking for status.
+  echo $! > $pidfile
+
+  echo "$name started."
+  return 0
 }
 
 stop() {
-    echo -n $"Stopping Carbon C Relay: "
-    killproc -p ${PID_FILE} -d 10 ${DAEMON}
-    RETVAL=$?
-    echo
-    [ $RETVAL = 0 ] && rm -f ${LOCK_FILE} ${PID_FILE}
-    return $RETVAL
+  # Try a few times to kill TERM the program
+  if status ; then
+    pid=`cat "$pidfile"`
+    echo "Killing $name (pid $pid) with SIGTERM"
+    kill -TERM $pid
+    # Wait for it to exit.
+    for i in 1 2 3 4 5 ; do
+      echo "Waiting $name (pid $pid) to die..."
+      status || break
+      sleep 1
+    done
+    if status ; then
+      echo "$name stop failed; still running."
+    else
+      echo "$name stopped."
+    fi
+  fi
 }
 
-check_status() {
-    status -p ${PID_FILE} ${DAEMON}
-    RETVAL=$?
-    return $RETVAL
+status() {
+  if [ -f "$pidfile" ] ; then
+    pid=`cat "$pidfile"`
+    if kill -0 $pid > /dev/null 2> /dev/null ; then
+      # process by this pid is running.
+      # It may not be our pid, but that's what you get with just pidfiles.
+      # TODO(sissel): Check if this process seems to be the same as the one we
+      # expect. It'd be nice to use flock here, but flock uses fork, not exec,
+      # so it makes it quite awkward to use in this case.
+      return 0
+    else
+      return 2 # program is dead but pid file exists
+    fi
+  else
+    return 3 # program is not running
+  fi
 }
 
 reload() {
   echo -n $"Reload Carbon C Relay: "
-  killproc -p ${PID_FILE} -d 10 ${DAEMON} -HUP
+  kill -HUP -p `cat "$pidfile"`
   RETVAL=$?
   echo
 }
 
+force_stop() {
+  if status ; then
+    stop
+    status && kill -KILL `cat "$pidfile"`
+  fi
+}
+
+
 case "$1" in
-    start)
-        start
-        ;;
-    stop)
-        stop
-        ;;
-    status)
-	      check_status
-        ;;
-    reload)
-        reload
-        ;;
-    restart)
-        stop
-        start
-        ;;
-    *)
-        N=/etc/init.d/${NAME}
-        echo "Usage: $N {start|stop|status|restart|reload}" >&2
-        RETVAL=2
-        ;;
+  start)
+    status
+    code=$?
+    if [ $code -eq 0 ]; then
+      echo "$name is already running"
+    else
+      start
+      code=$?
+    fi
+    exit $code
+    ;;
+  stop) stop ;;
+  force-stop) force_stop ;;
+  status)
+    status
+    code=$?
+    if [ $code -eq 0 ] ; then
+      echo "$name is running"
+    else
+      echo "$name is not running"
+    fi
+    exit $code
+    ;;
+  restart)
+
+    stop && start
+    ;;
+  *)
+    echo "Usage: $SCRIPTNAME {start|stop|force-stop|status|restart}" >&2
+    exit 3
+  ;;
 esac
 
-exit ${RETVAL}
+exit $?
